name: tests

on:
  push:
    branches:
      - master
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    container: golang:1.22

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          go test ./... -coverprofile cover.out
          go tool cover -html=cover.out -o=cover.html
        env:
          TEST_DATABASE_URI: "postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"

      - name: Deploy test coverage
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cover.html
